services:
  test-repo:
    image: nginx:alpine
    ports:
      - "52221:80"
    volumes:
      - ./test/repo:/usr/share/nginx/html:ro
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    command: |
      sh -c "
      echo 'server {
        listen 80;
        server_name localhost;
        root /usr/share/nginx/html;

        location / {
          try_files \$$uri \$$uri/ =404;
          add_header Access-Control-Allow-Origin *;
          add_header Access-Control-Allow-Methods GET,POST,OPTIONS;
          add_header Access-Control-Allow-Headers DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range;
        }
      }' > /etc/nginx/conf.d/default.conf &&
      nginx -g 'daemon off;'
      "
    restart: no
