name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.24'
          check-latest: true
          cache: true

      - name: Install Task
        run: go install github.com/go-task/task/v3/cmd/task@latest

      - name: Check out code
        uses: actions/checkout@v5

      - name: Run tests
        run: task test

  integration-test:
    name: Integration Test (${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest, ubuntu-24.04-arm]

    steps:
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.24'
          check-latest: true
          cache: true

      - name: Install Task
        run: go install github.com/go-task/task/v3/cmd/task@latest

      - name: Check out code
        uses: actions/checkout@v5

      - name: Run tests
        run: task test-integration

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.24'
          check-latest: true

      - name: Check out code
        uses: actions/checkout@v5

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
          args: --timeout 5m
