name: Integration Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  integration-test:
    name: Integration Test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          check-latest: true

      - name: Check out code
        uses: actions/checkout@v4

      - name: Start HTTP server for test index
        uses: Eun/http-server-action@v1.0.12
        with:
          port: 52221
          directory: ${{ github.workspace }}/test/repo

      - name: Build gotya
        run: |
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            go build -o gotya.exe ./cli/gotya
            echo "GOTYA_BIN=gotya.exe" >> $GITHUB_ENV
          else
            go build -o gotya ./cli/gotya
            echo "GOTYA_BIN=./gotya" >> $GITHUB_ENV
          fi

      - name: Run integration tests
        run: |
          # Test repository listing
          ${{ env.GOTYA_BIN }} --config test/config.yaml config repo list
          
          # Sync repo
          ${{ env.GOTYA_BIN }} --config test/config.yaml sync
          
          # Test package search
          ${{ env.GOTYA_BIN }} --config test/config.yaml search test-package
          
          # Test package installation
          ${{ env.GOTYA_BIN }} --config test/config.yaml install test-package
          
          # Verify installation
          ${{ env.GOTYA_BIN }} --config test/config.yaml list --installed | grep test-package
          
          # Test package update
          ${{ env.GOTYA_BIN }} --config test/config.yaml update test-package
          
          # Test package uninstallation
          ${{ env.GOTYA_BIN }} --config test/config.yaml uninstall test-package
          
          # Verify uninstallation
          if ${{ env.GOTYA_BIN }} --config test/config.yaml list --installed | grep -q test-package; then
            echo "Package was not properly uninstalled"
            exit 1
          fi
          
          # Test cache operations
          ${{ env.GOTYA_BIN }} --config test/config.yaml cache clean --all
          
          # Test configuration
          ${{ env.GOTYA_BIN }} --config test/config.yaml config show


